title: Isabel Prado # your name 
logo: "/images/me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <a href="https://www.linkedin.com/in/isabelprado/">LinkedIn</a>  
  <br>
  
  <a href="pdf/Prado, Isabel Resume.pdf" class="btn btn--info">Resume</a>  
  <br>
  
  <a href="https://github.com/isp223">Github</a>  
  <br>

  
theme: jekyll-theme-minimal
